backend_project/app.py
from flask import Flask, render_template
from views import my_view

app = Flask(__name__)
app.register_blueprint(my_view)

@app.errorhandler(404)
def page_not_found(e):
    return render_template("404.html", e=e)

if __name__=="__main__":
    app.run(debug=True, port=8000)

backend_project/views.py
from flask import Flask, render_template, Blueprint, redirect, url_for 

my_view = Blueprint('my_view', __name__)


@my_view.route('/')
def index():
    return render_template("index.html")

@my_view.route('/page1')
def page1():
    return render_template("page1.html")

@my_view.route('/page2')
def page2():
    return render_template("page2.html")

@my_view.route('/page3')
def page3():
    return render_template("page3.html")

@my_view.route('/page4')
def page4():
    return render_template("page4.html")

@my_view.route('/page5')
def page5():
    return render_template("page5.html")

@my_view.route('/home')
@my_view.route('/js')
@my_view.route('/javascript')
def index_redirect():
    return redirect(url_for("my_view.index"))

@my_view.route('/admin')
def admin():
    return render_template("admin.html")

backend_project/templates/admin.html
{% extends 'base.html' %}

{% block content %}
<h3>admin</h3>
{% endblock %}

backend_project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename = 'style.css')}}">
    <script src="{{url_for('static', filename = 'app.js')}}"></script>
    <title>My First Flask App</title>
</head>
<body>
    <h1>Welcome to my Flask App</h1>
    {% block content %}
    {% endblock %}

<nav>
    <a href="{{ url_for('my_view.index')}}">Index</a>
    <a href="{{ url_for('my_view.page1')}}">Page 1</a>
    <a href="{{ url_for('my_view.page2')}}">Page 2</a>
    <a href="{{ url_for('my_view.page3')}}">Page 3</a>
    <a href="{{ url_for('my_view.page4')}}">Page 4</a>
    <a href="{{ url_for('my_view.page5')}}">Page 5</a>
    <a href="{{ url_for('my_view.admin')}}">Admin</a>
</nav>
</body>
</html>

backend_project/templates/index.html
{% extends 'base.html' %}

{% block content %}
<body onload="checkCookies()">
    <div class="flex-container-h">
    <div>
    <h1>JavaScript Events</h1>
    <div class="flex-container-h">
        <button>Dark Mode</button>
    </div>
    <h2>Innovate Coding</h2>
    <p id="intro-text">This is an interactive website for demonstrating a selection of events in JavaScript.</p>

    <br>

    <div class="main-box">
    <h3 class="main-title">onclick Events</h3>
    <p class="main-text">This is an event that occurs as a result of the user 'clicking' a specific element.</p>
    <p onclick="changeText(this)" class="example-text">click this text to change it</p>
    <div class="flex-container-h2">
    <button onclick="displayDate(date)" class="example-button">Display Date</button>
    <p class="example-text" id="date"></p>
    </div>
    </div>

    <br>
    <br>

    <div class="main-box">
    <h3 class="main-title">onload Events</h3>
    <p class="main-text">This is an event that occurs as soon as the user has loaded the web page.</p>
    <p class="example-text" id="cookie"></p>
    </div>

    <br>
    <br>

    <div class="main-box">
    <h3 class="main-title">Mouse Events</h3>
    <p class="main-text">This is an event that occurs when the user moves their cursor over a specific element.</p>
    <div class="flex-container-h3">
        <div onmouseover="mOver(this)" onmouseout="mOut(this)" class="colour-box example-text">
        </div>
        <div onmouseover="mOver(this)" onmouseout="mOut(this)" class="colour-box example-text">
        </div>
        <div onmouseover="mOver(this)" onmouseout="mOut(this)" class="colour-box example-text">
        </div>
    </div>
    </div>

    <br>
    <br>

    <div class="main-box">
    <h3 class="main-title">Extra:</h3>
        <p class="main-text">Additional features that can be used in developing a website with JavaScript.</p>
        <h4 class="main-text">Alert</h4>

        <p class="main-text">An alert is used to notify the user via a pop-up window.</p>
        <button onclick="sendAlert()" class="example-button">Display Host Name</button>
        <h4 class="main-text">Toggle</h4>
        <p class="main-text">TBC</p>
    </div>

    <br>
    <br>

    </div>
    </div>
</body>
{% endblock %}

backend_project/templates/page1.html
{% extends 'base.html' %}

{% block content %}
<h3>And inbetween is where the content goes</h3>
{% endblock %}

backend_project/templates/page2.html
{% extends 'base.html' %}

{% block content %}
<h3>And inbetween is where the content goes</h3>
{% endblock %}

backend_project/templates/page3.html
{% extends 'base.html' %}

{% block content %}
<h3>And inbetween is where the content goes</h3>
{% endblock %}

backend_project/templates/page4.html
{% extends 'base.html' %}

{% block content %}
<h3>And inbetween is where the content goes</h3>
{% endblock %}

backend_project/templates/page5.html
{% extends 'base.html' %}

{% block content %}
<h3>And inbetween is where the content goes</h3>
{% endblock %}