flask_template/app.py
from flask import Flask, render_template
from views import my_view

app = Flask(__name__)
app.register_blueprint(my_view)

if __name__=="__main__":
    app.run(debug=True, port=8000)

flask_template/views.py
from flask import Flask, render_template, Blueprint

my_view = Blueprint('my_view', __name__)

@my_view.route('/')
def index():
    return render_template("index.html")

@my_view.route('/home')
def home():
    return '<h1>This is Chantelle\'s app</h1>'

@my_view.route('/about')
def about():
    return '<h1>About Me</h1>'

flask_template/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h3>And inbetween is where the content goes</h3>
{% endblock %}

flask_template/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My First Flask App</title>
</head>
<body>
    <h1>Welcome to my Flask App</h1>
    {% block content %}
    {% endblock %}

<nav>
    <a href="{{ url_for('my_view.index')}}">Index</a>
    <a href="{{ url_for('my_view.home')}}">Home</a>
    <a href="{{ url_for('my_view.about')}}">About</a>


</nav>
</body>
</html>

flask_template/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h3>And inbetween is where the content goes</h3>
{% endblock %}

flask_template/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h3>index</h3>
{% endblock %}